import type { ComponentSchema, FieldSchema } from "@/types";

export type { ComponentSchema, FieldSchema };

export const componentRegistry: ComponentSchema[] = [
  {
    type: "hero",
    label: "Hero Section",
    description: "A large hero section with heading, subheading, and CTA",
    icon: "Layout",
    fields: [
      {
        name: "heading",
        label: "Heading",
        type: "text",
        required: true,
        defaultValue: "Welcome to Our Site",
      },
      {
        name: "subheading",
        label: "Subheading",
        type: "textarea",
        required: false,
        defaultValue: "Discover amazing spaces crafted with trust",
      },
      {
        name: "buttonText",
        label: "Button Text",
        type: "text",
        required: false,
        defaultValue: "Get Started",
      },
      {
        name: "buttonUrl",
        label: "Button URL",
        type: "url",
        required: false,
        defaultValue: "#contact",
      },
      {
        name: "image",
        label: "Background Image",
        type: "media",
        required: false,
      },
      {
        name: "overlay",
        label: "Show Overlay",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
    ],
  },
  {
    type: "features",
    label: "Features Grid",
    description: "A grid of feature cards with icons",
    icon: "Grid",
    fields: [
      {
        name: "title",
        label: "Section Title",
        type: "text",
        required: true,
        defaultValue: "Our Features",
      },
      {
        name: "subtitle",
        label: "Section Subtitle",
        type: "textarea",
        required: false,
      },
      {
        name: "features",
        label: "Features",
        type: "array",
        required: true,
      },
    ],
  },
  {
    type: "about",
    label: "About Section",
    description: "About section with image and text",
    icon: "User",
    fields: [
      {
        name: "label",
        label: "Label",
        type: "text",
        required: false,
        defaultValue: "Our Story",
      },
      {
        name: "heading",
        label: "Heading",
        type: "text",
        required: true,
        defaultValue: "Where trust becomes the foundation",
      },
      {
        name: "content",
        label: "Content",
        type: "richtext",
        required: true,
      },
      {
        name: "image",
        label: "Image",
        type: "media",
        required: false,
      },
      {
        name: "imagePosition",
        label: "Image Position",
        type: "select",
        required: false,
        defaultValue: "right",
        options: [
          { label: "Left", value: "left" },
          { label: "Right", value: "right" },
        ],
      },
      {
        name: "quote",
        label: "Quote",
        type: "textarea",
        required: false,
      },
      {
        name: "quoteAuthor",
        label: "Quote Author",
        type: "text",
        required: false,
      },
    ],
  },
  {
    type: "services",
    label: "Services Section",
    description: "Showcase your services",
    icon: "Briefcase",
    fields: [
      {
        name: "title",
        label: "Section Title",
        type: "text",
        required: true,
        defaultValue: "Our Services",
      },
      {
        name: "subtitle",
        label: "Section Subtitle",
        type: "textarea",
        required: false,
      },
      {
        name: "services",
        label: "Services",
        type: "array",
        required: true,
      },
    ],
  },
  {
    type: "portfolio",
    label: "Portfolio Gallery",
    description: "Display portfolio items in a grid",
    icon: "Image",
    fields: [
      {
        name: "title",
        label: "Section Title",
        type: "text",
        required: true,
        defaultValue: "Our Work",
      },
      {
        name: "subtitle",
        label: "Section Subtitle",
        type: "textarea",
        required: false,
      },
      {
        name: "items",
        label: "Portfolio Items",
        type: "array",
        required: true,
      },
    ],
  },
  {
    type: "testimonials",
    label: "Testimonials",
    description: "Customer testimonials slider",
    icon: "MessageSquare",
    fields: [
      {
        name: "title",
        label: "Section Title",
        type: "text",
        required: true,
        defaultValue: "What Our Clients Say",
      },
      {
        name: "testimonials",
        label: "Testimonials",
        type: "array",
        required: true,
      },
    ],
  },
  {
    type: "team",
    label: "Team Section",
    description: "Display team members",
    icon: "Users",
    fields: [
      {
        name: "title",
        label: "Section Title",
        type: "text",
        required: true,
        defaultValue: "Our Team",
      },
      {
        name: "subtitle",
        label: "Section Subtitle",
        type: "textarea",
        required: false,
      },
      {
        name: "members",
        label: "Team Members",
        type: "array",
        required: true,
      },
    ],
  },
  {
    type: "faq",
    label: "FAQ Section",
    description: "Frequently asked questions accordion",
    icon: "HelpCircle",
    fields: [
      {
        name: "title",
        label: "Section Title",
        type: "text",
        required: true,
        defaultValue: "Frequently Asked Questions",
      },
      {
        name: "faqs",
        label: "FAQs",
        type: "array",
        required: true,
      },
    ],
  },
  {
    type: "contact",
    label: "Contact Section",
    description: "Contact form with info",
    icon: "Mail",
    fields: [
      {
        name: "title",
        label: "Section Title",
        type: "text",
        required: true,
        defaultValue: "Get In Touch",
      },
      {
        name: "subtitle",
        label: "Section Subtitle",
        type: "textarea",
        required: false,
      },
      {
        name: "showForm",
        label: "Show Contact Form",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
      {
        name: "address",
        label: "Address",
        type: "textarea",
        required: false,
      },
      {
        name: "phone",
        label: "Phone",
        type: "text",
        required: false,
      },
      {
        name: "email",
        label: "Email",
        type: "text",
        required: false,
      },
    ],
  },
  {
    type: "cta",
    label: "Call to Action",
    description: "Prominent call-to-action banner",
    icon: "Megaphone",
    fields: [
      {
        name: "heading",
        label: "Heading",
        type: "text",
        required: true,
        defaultValue: "Ready to get started?",
      },
      {
        name: "subheading",
        label: "Subheading",
        type: "textarea",
        required: false,
      },
      {
        name: "buttonText",
        label: "Button Text",
        type: "text",
        required: true,
        defaultValue: "Contact Us",
      },
      {
        name: "buttonUrl",
        label: "Button URL",
        type: "url",
        required: true,
        defaultValue: "/contact",
      },
      {
        name: "style",
        label: "Style",
        type: "select",
        required: false,
        defaultValue: "primary",
        options: [
          { label: "Primary", value: "primary" },
          { label: "Secondary", value: "secondary" },
          { label: "Dark", value: "dark" },
        ],
      },
    ],
  },
  {
    type: "content",
    label: "Content Block",
    description: "Simple rich text content block",
    icon: "FileText",
    fields: [
      {
        name: "content",
        label: "Content",
        type: "richtext",
        required: true,
      },
      {
        name: "alignment",
        label: "Alignment",
        type: "select",
        required: false,
        defaultValue: "left",
        options: [
          { label: "Left", value: "left" },
          { label: "Center", value: "center" },
          { label: "Right", value: "right" },
        ],
      },
    ],
  },
  {
    type: "about_hero",
    label: "About Hero",
    description: "Hero section for About page with background image",
    icon: "Image",
    fields: [
      {
        name: "heading",
        label: "Heading",
        type: "text",
        required: true,
        defaultValue: "About Aliignspace",
      },
      {
        name: "subheading",
        label: "Subheading",
        type: "textarea",
        required: false,
        defaultValue: "Our Core team is specialised in interiors with 10 years of experience",
      },
      {
        name: "label",
        label: "Label",
        type: "text",
        required: false,
        defaultValue: "Who We Are",
        description: "Small label above the heading",
      },
      {
        name: "backgroundImage",
        label: "Background Image",
        type: "media",
        required: false,
      },
      {
        name: "alignment",
        label: "Content Alignment",
        type: "select",
        required: false,
        defaultValue: "center",
        options: [
          { label: "Center", value: "center" },
          { label: "Left", value: "left" },
          { label: "Right", value: "right" },
        ],
      },
      {
        name: "minHeight",
        label: "Minimum Height",
        type: "select",
        required: false,
        defaultValue: "70vh",
        options: [
          { label: "50vh", value: "50vh" },
          { label: "60vh", value: "60vh" },
          { label: "70vh", value: "70vh" },
          { label: "80vh", value: "80vh" },
          { label: "90vh", value: "90vh" },
          { label: "100vh", value: "100vh" },
        ],
      },
      {
        name: "overlayOpacity",
        label: "Overlay Opacity",
        type: "number",
        required: false,
        defaultValue: 70,
        description: "Background overlay darkness (0-100)",
      },
      {
        name: "showScrollIndicator",
        label: "Show Scroll Indicator",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
    ],
  },
  {
    type: "about_story",
    label: "About Story",
    description: "Company story section with image and quote",
    icon: "BookOpen",
    fields: [
      {
        name: "variant",
        label: "Section Variant",
        type: "select",
        required: false,
        defaultValue: "story",
        options: [
          { label: "Story (Two Column)", value: "story" },
          { label: "Mission (Single Column)", value: "mission" },
        ],
      },
      {
        name: "label",
        label: "Label",
        type: "text",
        required: false,
        defaultValue: "Our Story",
        description: "Small label above the heading",
      },
      {
        name: "heading",
        label: "Heading",
        type: "text",
        required: true,
        defaultValue: "Where trust becomes the foundation",
      },
      {
        name: "accentWord",
        label: "Accent Word",
        type: "text",
        required: false,
        description: "Word to highlight in terracotta color",
      },
      {
        name: "content",
        label: "Content",
        type: "richtext",
        required: true,
        defaultValue: "<p>At ALIIGNSPACE, we believe that every home tells a story.</p>",
        description: "Main content (HTML supported)",
      },
      {
        name: "image",
        label: "Story Image",
        type: "media",
        required: false,
      },
      {
        name: "imageAlt",
        label: "Image Alt Text",
        type: "text",
        required: false,
        description: "Accessibility text for the image",
      },
      {
        name: "imagePosition",
        label: "Image Position",
        type: "select",
        required: false,
        defaultValue: "left",
        options: [
          { label: "Left", value: "left" },
          { label: "Right", value: "right" },
        ],
      },
      {
        name: "quote",
        label: "Quote",
        type: "textarea",
        required: false,
        description: "Optional pull quote",
      },
      {
        name: "quoteAuthor",
        label: "Quote Author",
        type: "text",
        required: false,
        description: "Author of the quote",
      },
      {
        name: "backgroundColor",
        label: "Background Color",
        type: "select",
        required: false,
        defaultValue: "cream",
        options: [
          { label: "Cream", value: "cream" },
          { label: "White", value: "white" },
          { label: "Dark", value: "dark" },
        ],
      },
      {
        name: "spacing",
        label: "Section Spacing",
        type: "select",
        required: false,
        defaultValue: "normal",
        options: [
          { label: "Compact", value: "compact" },
          { label: "Normal", value: "normal" },
          { label: "Spacious", value: "spacious" },
        ],
      },
      {
        name: "showExperienceBadge",
        label: "Show Experience Badge",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
      {
        name: "experienceYears",
        label: "Experience Years",
        type: "text",
        required: false,
        defaultValue: "10+",
      },
      {
        name: "experienceLabel",
        label: "Experience Label",
        type: "text",
        required: false,
        defaultValue: "Years Experience",
      },
    ],
  },
  {
    type: "about_mission_vision",
    label: "Mission & Vision",
    description: "Mission and Vision cards section",
    icon: "Target",
    fields: [
      {
        name: "mission",
        label: "Mission",
        type: "object",
        required: true,
      },
      {
        name: "vision",
        label: "Vision",
        type: "object",
        required: true,
      },
    ],
  },
  {
    type: "about_stats",
    label: "About Stats",
    description: "Statistics section for About page",
    icon: "BarChart3",
    fields: [
      {
        name: "title",
        label: "Section Title",
        type: "text",
        required: true,
        defaultValue: "Our Impact",
      },
      {
        name: "subtitle",
        label: "Section Subtitle",
        type: "textarea",
        required: false,
        defaultValue: "Numbers that reflect our commitment to excellence",
      },
      {
        name: "stats",
        label: "Statistics",
        type: "array",
        required: true,
      },
    ],
  },
  {
    type: "about_team",
    label: "About Team",
    description: "Team members grid for About page",
    icon: "Users",
    fields: [
      {
        name: "title",
        label: "Section Title",
        type: "text",
        required: true,
        defaultValue: "Meet Our Team",
      },
      {
        name: "subtitle",
        label: "Section Subtitle",
        type: "textarea",
        required: false,
        defaultValue: "The creative minds behind every beautiful space",
      },
      {
        name: "members",
        label: "Team Members",
        type: "array",
        required: true,
      },
    ],
  },
  {
    type: "about_values",
    label: "About Values",
    description: "Company values grid section",
    icon: "Heart",
    fields: [
      {
        name: "title",
        label: "Section Title",
        type: "text",
        required: true,
        defaultValue: "Our Values",
      },
      {
        name: "subtitle",
        label: "Section Subtitle",
        type: "textarea",
        required: false,
        defaultValue: "The principles that guide everything we do",
      },
      {
        name: "values",
        label: "Values",
        type: "array",
        required: true,
      },
    ],
  },
  {
    type: "home_about_premium",
    label: "Home About Premium",
    description: "Premium about section with artistic image collage and animations",
    icon: "Sparkles",
    fields: [
      {
        name: "label",
        label: "Label",
        type: "text",
        required: false,
        defaultValue: "About Us",
      },
      {
        name: "heading",
        label: "Heading",
        type: "text",
        required: true,
        defaultValue: "Where Trust Becomes the Foundation",
      },
      {
        name: "accentWord",
        label: "Accent Word",
        type: "text",
        required: false,
        defaultValue: "Trust",
      },
      {
        name: "content",
        label: "Content",
        type: "richtext",
        required: true,
        defaultValue: "<p>At ALIIGNSPACE, we believe that every home tells a story. Our passion lies in crafting spaces that not only reflect your personality but also enhance your daily life.</p>",
      },
      {
        name: "images",
        label: "Images",
        type: "array",
        required: false,
      },
      {
        name: "quote",
        label: "Quote",
        type: "textarea",
        required: false,
        defaultValue: "Design is not just what it looks like and feels like. Design is how it works.",
      },
      {
        name: "quoteAuthor",
        label: "Quote Author",
        type: "text",
        required: false,
        defaultValue: "Steve Jobs",
      },
      {
        name: "stats",
        label: "Statistics",
        type: "array",
        required: false,
      },
      {
        name: "layout",
        label: "Layout Style",
        type: "select",
        required: false,
        defaultValue: "split",
        options: [
          { label: "Split (60/40)", value: "split" },
          { label: "Image Collage", value: "collage" },
          { label: "Full Width", value: "fullwidth" },
          { label: "Timeline", value: "timeline" },
        ],
      },
      {
        name: "showVideo",
        label: "Show Video Play Button",
        type: "boolean",
        required: false,
        defaultValue: false,
      },
      {
        name: "videoUrl",
        label: "Video URL (YouTube embed)",
        type: "url",
        required: false,
      },
    ],
  },
  {
    type: "why-aliignspace-premium",
    label: "Why Aliignspace Premium",
    description: "Premium 'Why Choose Us' section with animated counters, 3D tilt cards, and glass-morphism effects",
    icon: "Star",
    fields: [
      {
        name: "eyebrow",
        label: "Eyebrow Text",
        type: "text",
        required: false,
        defaultValue: "Why Choose Us",
      },
      {
        name: "title",
        label: "Main Heading",
        type: "text",
        required: true,
        defaultValue: "The ALIIGNSPACE Difference",
      },
      {
        name: "accentWord",
        label: "Accent Word (for animated highlight)",
        type: "text",
        required: false,
        defaultValue: "ALIIGNSPACE",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
        defaultValue: "Crafting extraordinary spaces built on trust, quality, and timeless design principles since 2015.",
      },
      {
        name: "quote",
        label: "Quote Text",
        type: "textarea",
        required: false,
        defaultValue: "We don't just design spaces; we craft experiences that transform houses into homes.",
      },
      {
        name: "quoteAuthor",
        label: "Quote Author Name",
        type: "text",
        required: false,
        defaultValue: "Ar. Samhitha Nagasamudra",
      },
      {
        name: "quoteRole",
        label: "Quote Author Role",
        type: "text",
        required: false,
        defaultValue: "Founder & Principal Designer",
      },
      {
        name: "founderImage",
        label: "Founder Image",
        type: "media",
        required: false,
      },
      {
        name: "features",
        label: "Feature Cards",
        type: "array",
        required: false,
      },
      {
        name: "theme",
        label: "Theme",
        type: "select",
        required: false,
        defaultValue: "dark",
        options: [
          { label: "Dark (Premium)", value: "dark" },
          { label: "Light (Clean)", value: "light" },
        ],
      },
      {
        name: "showFloatingElements",
        label: "Show Floating Decorative Elements",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
      {
        name: "showAnimatedBackground",
        label: "Show Animated Gradient Background",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
    ],
  },
  {
    type: "video-testimonials",
    label: "Video Testimonials",
    description: "Elegant video testimonials carousel with portrait cards",
    icon: "Video",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        defaultValue: "Hear It from Those Who Experienced It",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "text",
        required: false,
        defaultValue: "Real stories from real homeowners",
      },
      {
        name: "eyebrow",
        label: "Eyebrow Text",
        type: "text",
        required: false,
        defaultValue: "Client Stories",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        required: false,
        defaultValue: "Watch authentic testimonials from our satisfied clients.",
      },
      {
        name: "videos",
        label: "Video Testimonials",
        type: "array",
        required: true,
      },
      {
        name: "autoplay",
        label: "Auto-play Carousel",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
    ],
  },
  {
    type: "why-choose-us-premium",
    label: "Why Choose Us Premium",
    description: "Premium Why Choose Us section with glassmorphism cards",
    icon: "Star",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        defaultValue: "The ALIIGNSPACE Difference",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "text",
        required: false,
        defaultValue: "Why discerning homeowners choose us",
      },
      {
        name: "eyebrow",
        label: "Eyebrow Text",
        type: "text",
        required: false,
        defaultValue: "Why Choose Us",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        required: false,
      },
      {
        name: "quote",
        label: "Quote",
        type: "textarea",
        required: false,
      },
      {
        name: "quoteAuthor",
        label: "Quote Author",
        type: "text",
        required: false,
      },
      {
        name: "quoteRole",
        label: "Quote Author Role",
        type: "text",
        required: false,
      },
      {
        name: "founderImage",
        label: "Founder Image",
        type: "media",
        required: false,
      },
      {
        name: "features",
        label: "Features",
        type: "array",
        required: true,
      },
    ],
  },
  {
    type: "hero-premium",
    label: "Hero Premium",
    description: "Premium hero section with parallax and animations",
    icon: "Layout",
    fields: [
      {
        name: "heading",
        label: "Heading",
        type: "text",
        required: true,
        defaultValue: "Design That Feels Like You",
      },
      {
        name: "accentWord",
        label: "Accent Word",
        type: "text",
        required: false,
        defaultValue: "Feels",
      },
      {
        name: "subheading",
        label: "Subheading",
        type: "textarea",
        required: false,
        defaultValue: "Every home is personal. We design spaces that reflect your lifestyle.",
      },
      {
        name: "buttonText",
        label: "Primary Button Text",
        type: "text",
        required: false,
        defaultValue: "Get Free Consultation",
      },
      {
        name: "buttonUrl",
        label: "Primary Button URL",
        type: "url",
        required: false,
        defaultValue: "/contact",
      },
      {
        name: "secondaryButtonText",
        label: "Secondary Button Text",
        type: "text",
        required: false,
        defaultValue: "View Our Work",
      },
      {
        name: "secondaryButtonUrl",
        label: "Secondary Button URL",
        type: "url",
        required: false,
        defaultValue: "/portfolio",
      },
      {
        name: "image",
        label: "Background Image",
        type: "media",
        required: false,
      },
      {
        name: "videoUrl",
        label: "Video URL",
        type: "url",
        required: false,
      },
    ],
  },
  {
    type: "stats-floating",
    label: "Stats Floating",
    description: "Floating statistics bar with animated counters",
    icon: "BarChart",
    fields: [
      {
        name: "stats",
        label: "Statistics",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "portfolio-premium",
    label: "Portfolio Premium",
    description: "Premium portfolio gallery with filtering",
    icon: "Image",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        defaultValue: "Featured Projects",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
        defaultValue: "A glimpse of our latest transformations",
      },
      {
        name: "items",
        label: "Portfolio Items",
        type: "array",
        required: false,
      },
      {
        name: "maxItems",
        label: "Maximum Items to Show",
        type: "number",
        required: false,
        defaultValue: 3,
      },
      {
        name: "showViewAllButton",
        label: "Show View All Button",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
      {
        name: "showFilters",
        label: "Show Category Filters",
        type: "boolean",
        required: false,
        defaultValue: false,
      },
    ],
  },
  {
    type: "testimonials-premium",
    label: "Testimonials Premium",
    description: "Premium testimonials carousel with elegant cards",
    icon: "MessageCircle",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        defaultValue: "What Our Clients Say",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
      },
      {
        name: "eyebrow",
        label: "Eyebrow Text",
        type: "text",
        required: false,
        defaultValue: "Testimonials",
      },
      {
        name: "testimonials",
        label: "Testimonials",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "google-reviews",
    label: "Google Reviews",
    description: "Google reviews section with ratings",
    icon: "Star",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        defaultValue: "Loved by Homeowners Across Hyderabad",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
      },
      {
        name: "rating",
        label: "Rating",
        type: "text",
        required: false,
        defaultValue: "4.9",
      },
      {
        name: "reviewCount",
        label: "Review Count",
        type: "text",
        required: false,
        defaultValue: "50+",
      },
    ],
  },
  {
    type: "consultation",
    label: "Consultation CTA",
    description: "Consultation call-to-action section",
    icon: "Phone",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        defaultValue: "Book Your Free Consultation",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
      },
      {
        name: "buttonText",
        label: "Button Text",
        type: "text",
        required: false,
        defaultValue: "Schedule a Call",
      },
      {
        name: "buttonUrl",
        label: "Button URL",
        type: "url",
        required: false,
        defaultValue: "/contact",
      },
    ],
  },
  {
    type: "hero-clean",
    label: "Hero Clean",
    description: "Modern clean hero section with split layout",
    icon: "Layout",
    fields: [
      {
        name: "heading",
        label: "Heading",
        type: "text",
        required: true,
        defaultValue: "Crafting Spaces",
      },
      {
        name: "subheading",
        label: "Subheading",
        type: "text",
        required: false,
        defaultValue: "That Inspire",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        required: false,
        defaultValue: "We transform houses into dream homes with thoughtful design, quality craftsmanship, and a personal touch.",
      },
      {
        name: "buttonText",
        label: "Primary Button Text",
        type: "text",
        required: false,
        defaultValue: "Start Your Project",
      },
      {
        name: "buttonUrl",
        label: "Primary Button URL",
        type: "url",
        required: false,
        defaultValue: "/contact",
      },
      {
        name: "secondaryButtonText",
        label: "Secondary Button Text",
        type: "text",
        required: false,
        defaultValue: "View Portfolio",
      },
      {
        name: "secondaryButtonUrl",
        label: "Secondary Button URL",
        type: "url",
        required: false,
        defaultValue: "/portfolio",
      },
      {
        name: "image",
        label: "Hero Image",
        type: "media",
        required: false,
      },
      {
        name: "showVideoButton",
        label: "Show Video Button",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
    ],
  },
  {
    type: "stats-clean",
    label: "Stats Clean",
    description: "Clean minimal statistics section",
    icon: "BarChart",
    fields: [
      {
        name: "stats",
        label: "Statistics",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "services-clean",
    label: "Services Clean",
    description: "Modern services grid with images",
    icon: "Briefcase",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        defaultValue: "Our Services",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
        defaultValue: "Comprehensive interior solutions tailored to your needs",
      },
      {
        name: "services",
        label: "Services",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "portfolio-masonry",
    label: "Portfolio Masonry",
    description: "Masonry-style portfolio grid",
    icon: "Image",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        defaultValue: "Featured Projects",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
        defaultValue: "Explore our latest interior transformations",
      },
      {
        name: "items",
        label: "Portfolio Items",
        type: "array",
        required: false,
      },
      {
        name: "maxItems",
        label: "Maximum Items",
        type: "number",
        required: false,
        defaultValue: 5,
      },
      {
        name: "showViewAllButton",
        label: "Show View All Button",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
    ],
  },
  {
    type: "why-choose-clean",
    label: "Why Choose Us Clean",
    description: "Clean why choose us section with image",
    icon: "Star",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Why Choose Us",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "text",
        required: false,
        defaultValue: "The ALIIGNSPACE Difference",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        required: false,
      },
      {
        name: "features",
        label: "Features",
        type: "array",
        required: false,
      },
      {
        name: "image",
        label: "Image",
        type: "media",
        required: false,
      },
      {
        name: "quote",
        label: "Quote",
        type: "textarea",
        required: false,
      },
      {
        name: "quoteAuthor",
        label: "Quote Author",
        type: "text",
        required: false,
      },
      {
        name: "quoteRole",
        label: "Quote Author Role",
        type: "text",
        required: false,
      },
    ],
  },
  {
    type: "cta-clean",
    label: "CTA Clean",
    description: "Clean call-to-action section",
    icon: "Phone",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        defaultValue: "Ready to Transform Your Space?",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
        defaultValue: "Let's discuss your project and bring your vision to life.",
      },
      {
        name: "buttonText",
        label: "Button Text",
        type: "text",
        required: false,
        defaultValue: "Get Free Consultation",
      },
      {
        name: "buttonUrl",
        label: "Button URL",
        type: "url",
        required: false,
        defaultValue: "/contact",
      },
      {
        name: "showPhone",
        label: "Show Phone Button",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
      {
        name: "phoneNumber",
        label: "Phone Number",
        type: "text",
        required: false,
        defaultValue: "+91 90304 44503",
      },
    ],
  },

  // New V2 Components (Aertsen-inspired)
  {
    type: "stats-v2",
    label: "Stats V2 (Large Typography)",
    description: "Large typography statistics section inspired by premium studios",
    icon: "BarChart",
    fields: [
      {
        name: "stats",
        label: "Statistics",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "benefits-v2",
    label: "Benefits V2 (Numbered)",
    description: "Numbered benefits section (01, 02, 03, 04) with icons",
    icon: "ListOrdered",
    fields: [
      {
        name: "title",
        label: "Section Title",
        type: "text",
        required: false,
        defaultValue: "The ALIIGNSPACE Advantage",
      },
      {
        name: "subtitle",
        label: "Section Subtitle",
        type: "text",
        required: false,
        defaultValue: "Why Homeowners Trust Us",
      },
      {
        name: "benefits",
        label: "Benefits",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "projects-v2",
    label: "Projects V2 (Full-Width Showcase)",
    description: "Full-width project showcase slider with large images",
    icon: "Images",
    fields: [
      {
        name: "title",
        label: "Section Title",
        type: "text",
        required: false,
        defaultValue: "Our Work",
      },
      {
        name: "subtitle",
        label: "Section Subtitle",
        type: "text",
        required: false,
        defaultValue: "Finest Projects We've Crafted",
      },
      {
        name: "projects",
        label: "Projects",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "process-v2",
    label: "Process V2 (4 Steps)",
    description: "4-step process section with large numbers and icons",
    icon: "Workflow",
    fields: [
      {
        name: "title",
        label: "Section Title",
        type: "text",
        required: false,
        defaultValue: "Steps to give your home an ALIIGNSPACE Makeover",
      },
      {
        name: "subtitle",
        label: "Section Subtitle",
        type: "text",
        required: false,
        defaultValue: "Our Process",
      },
      {
        name: "steps",
        label: "Process Steps",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "craftsmanship-v2",
    label: "Craftsmanship V2",
    description: "Quality and craftsmanship section with features",
    icon: "Hammer",
    fields: [
      {
        name: "title",
        label: "Section Title",
        type: "text",
        required: false,
        defaultValue: "Where Craftsmanship Meets Technology",
      },
      {
        name: "subtitle",
        label: "Section Subtitle",
        type: "text",
        required: false,
        defaultValue: "Our Promise",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        required: false,
      },
      {
        name: "features",
        label: "Features",
        type: "array",
        required: false,
      },
      {
        name: "image",
        label: "Image",
        type: "media",
        required: false,
      },
    ],
  },

  // Aertsen Replication Components
  {
    type: "aertsen-hero-slider",
    label: "Aertsen Hero Slider",
    description: "Full-screen hero slider with Ken Burns effect and animated content",
    icon: "Images",
    fields: [
      {
        name: "slides",
        label: "Slides",
        type: "array",
        required: false,
      },
      {
        name: "autoPlayInterval",
        label: "Auto-play Interval (ms)",
        type: "number",
        required: false,
        defaultValue: 6000,
      },
    ],
  },
  {
    type: "aertsen-services-grid",
    label: "Aertsen Services Grid",
    description: "Numbered services grid with hover effects and icons",
    icon: "Grid3X3",
    fields: [
      {
        name: "label",
        label: "Label",
        type: "text",
        required: false,
        defaultValue: "What We Do",
      },
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Our",
      },
      {
        name: "accentWord",
        label: "Accent Word",
        type: "text",
        required: false,
        defaultValue: "Services",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
        defaultValue: "Comprehensive interior solutions for every space and style",
      },
      {
        name: "services",
        label: "Services",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-milestones",
    label: "Aertsen Milestones",
    description: "Company milestones timeline with year markers",
    icon: "Flag",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Our Journey",
      },
      {
        name: "milestones",
        label: "Milestones",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-why-choose",
    label: "Aertsen Why Choose",
    description: "Why choose us section with feature cards",
    icon: "Award",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Why Choose Us",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "text",
        required: false,
        defaultValue: "The ALIIGNSPACE Difference",
      },
      {
        name: "features",
        label: "Features",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-portfolio-slider",
    label: "Aertsen Portfolio Slider",
    description: "Full-width portfolio project showcase slider",
    icon: "Slideshow",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Our Work",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "text",
        required: false,
        defaultValue: "Finest Projects We've Crafted",
      },
      {
        name: "projects",
        label: "Projects",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-process-wheel",
    label: "Aertsen Process Wheel",
    description: "Circular process visualization with numbered steps",
    icon: "RefreshCw",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Steps to give your home an ALIIGNSPACE Makeover",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "text",
        required: false,
        defaultValue: "Our Process",
      },
      {
        name: "steps",
        label: "Process Steps",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-factory",
    label: "Aertsen Factory",
    description: "Factory showcase section with stats and image",
    icon: "Factory",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Our Factory",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "text",
        required: false,
        defaultValue: "Where craftsmanship comes to life",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        required: false,
      },
      {
        name: "image",
        label: "Factory Image",
        type: "media",
        required: false,
      },
      {
        name: "stats",
        label: "Stats",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-google-reviews",
    label: "Aertsen Google Reviews",
    description: "Google reviews display with ratings and testimonials",
    icon: "Star",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Loved by Homeowners Across Hyderabad",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
      },
      {
        name: "rating",
        label: "Rating",
        type: "number",
        required: false,
        defaultValue: 4.9,
      },
      {
        name: "reviewCount",
        label: "Review Count",
        type: "number",
        required: false,
        defaultValue: 127,
      },
      {
        name: "reviews",
        label: "Reviews",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-video-testimonials",
    label: "Aertsen Video Testimonials",
    description: "Video testimonial cards with thumbnails and quotes",
    icon: "Video",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Video Testimonials",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "text",
        required: false,
        defaultValue: "Hear from our happy clients",
      },
      {
        name: "videos",
        label: "Videos",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-final-cta",
    label: "Aertsen Final CTA",
    description: "Final call-to-action banner for page bottom",
    icon: "Megaphone",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Ready to Transform Your Space?",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
        defaultValue: "Book a free consultation with our design experts today.",
      },
      {
        name: "buttonText",
        label: "Button Text",
        type: "text",
        required: false,
        defaultValue: "Get Free Consultation",
      },
      {
        name: "buttonUrl",
        label: "Button URL",
        type: "url",
        required: false,
        defaultValue: "/contact",
      },
    ],
  },
  {
    type: "aertsen-faq",
    label: "Aertsen FAQ",
    description: "FAQ accordion section for common questions",
    icon: "HelpCircle",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Frequently Asked Questions",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
        defaultValue: "Everything you need to know about our services",
      },
      {
        name: "faqs",
        label: "FAQs",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-about-hero",
    label: "Aertsen About Hero",
    description: "About page hero with serif typography and accent word",
    icon: "Layout",
    fields: [
      {
        name: "eyebrow",
        label: "Eyebrow",
        type: "text",
        required: false,
        defaultValue: "About Us",
      },
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Crafting Interiors with",
      },
      {
        name: "accentWord",
        label: "Accent Word",
        type: "text",
        required: false,
        defaultValue: "Purpose",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
        defaultValue: "We believe every space has a story.",
      },
    ],
  },
  {
    type: "aertsen-who-we-are",
    label: "Aertsen Who We Are",
    description: "Who we are section with stats and image",
    icon: "Users",
    fields: [
      {
        name: "label",
        label: "Label",
        type: "text",
        required: false,
        defaultValue: "Who We Are",
      },
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Designing spaces that reflect",
      },
      {
        name: "accentWord",
        label: "Accent Word",
        type: "text",
        required: false,
        defaultValue: "you",
      },
      {
        name: "body",
        label: "Body Paragraphs",
        type: "array",
        required: false,
      },
      {
        name: "stats",
        label: "Stats",
        type: "array",
        required: false,
      },
      {
        name: "image",
        label: "Image",
        type: "media",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-story",
    label: "Aertsen Story",
    description: "Company story section with narrative and image",
    icon: "BookOpen",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Our Story",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "text",
        required: false,
        defaultValue: "From a small studio to a trusted name in interiors",
      },
      {
        name: "content",
        label: "Content",
        type: "richtext",
        required: false,
      },
      {
        name: "image",
        label: "Image",
        type: "media",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-vision-mission",
    label: "Aertsen Vision & Mission",
    description: "Vision and mission cards section",
    icon: "Target",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Vision & Mission",
      },
      {
        name: "vision",
        label: "Vision",
        type: "textarea",
        required: false,
      },
      {
        name: "mission",
        label: "Mission",
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-promises",
    label: "Aertsen Promises",
    description: "Company promises grid with icons",
    icon: "ShieldCheck",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Our Promises",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
      },
      {
        name: "promises",
        label: "Promises",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-founders",
    label: "Aertsen Founders",
    description: "Founders profile cards with bio and image",
    icon: "Users",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Meet Our Founders",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
      },
      {
        name: "founders",
        label: "Founders",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-timeline",
    label: "Aertsen Timeline",
    description: "Company history timeline with events",
    icon: "Clock",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Our Journey",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
      },
      {
        name: "events",
        label: "Events",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-factory-video",
    label: "Aertsen Factory Video",
    description: "Factory tour video section with thumbnail",
    icon: "PlayCircle",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Inside Our Factory",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
      },
      {
        name: "videoUrl",
        label: "Video URL",
        type: "url",
        required: false,
      },
      {
        name: "thumbnail",
        label: "Thumbnail Image",
        type: "media",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-about-cta",
    label: "Aertsen About CTA",
    description: "Call-to-action section for about page",
    icon: "ArrowRightCircle",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Ready to Begin Your Journey?",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
      },
      {
        name: "buttonText",
        label: "Button Text",
        type: "text",
        required: false,
        defaultValue: "Book a Consultation",
      },
      {
        name: "buttonUrl",
        label: "Button URL",
        type: "url",
        required: false,
        defaultValue: "/contact",
      },
    ],
  },
  {
    type: "aertsen-services-hero",
    label: "Aertsen Services Hero",
    description: "Services page hero with accent typography",
    icon: "Layout",
    fields: [
      {
        name: "eyebrow",
        label: "Eyebrow",
        type: "text",
        required: false,
        defaultValue: "Our Services",
      },
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Interior Solutions Crafted with",
      },
      {
        name: "accentWord",
        label: "Accent Word",
        type: "text",
        required: false,
        defaultValue: "Care",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-services-cards",
    label: "Aertsen Services Cards",
    description: "Services cards grid with images and icons",
    icon: "Grid3X3",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "What We Offer",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
      },
      {
        name: "services",
        label: "Services",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-services-cta",
    label: "Aertsen Services CTA",
    description: "Services page call-to-action section",
    icon: "Phone",
    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Not Sure Where to Start?",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
      },
      {
        name: "buttonText",
        label: "Button Text",
        type: "text",
        required: false,
        defaultValue: "Get Free Consultation",
      },
      {
        name: "buttonUrl",
        label: "Button URL",
        type: "url",
        required: false,
        defaultValue: "/contact",
      },
    ],
  },
  {
    type: "aertsen-portfolio-hero",
    label: "Aertsen Portfolio Hero",
    description: "Portfolio page hero with serif typography",
    icon: "Layout",
    fields: [
      {
        name: "eyebrow",
        label: "Eyebrow",
        type: "text",
        required: false,
        defaultValue: "Our Work",
      },
      {
        name: "title",
        label: "Title",
        type: "text",
        required: false,
        defaultValue: "Crafting Interiors with",
      },
      {
        name: "accentWord",
        label: "Accent Word",
        type: "text",
        required: false,
        defaultValue: "Purpose",
      },
      {
        name: "subtitle",
        label: "Subtitle",
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-project-list",
    label: "Aertsen Project List",
    description: "Alternating project list with image sliders",
    icon: "List",
    fields: [
      {
        name: "projects",
        label: "Projects",
        type: "array",
        required: false,
      },
    ],
  },
  {
    type: "aertsen-project-detail",
    label: "Aertsen Project Detail",
    description: "Individual project detail page content",
    icon: "FileImage",
    fields: [
      {
        name: "title",
        label: "Project Title",
        type: "text",
        required: true,
        defaultValue: "Project Title",
      },
      {
        name: "location",
        label: "Location",
        type: "text",
        required: true,
        defaultValue: "Hyderabad",
      },
      {
        name: "description",
        label: "Description",
        type: "richtext",
        required: true,
      },
      {
        name: "gallery",
        label: "Gallery Images",
        type: "array",
        required: true,
      },
      {
        name: "mainVideoUrl",
        label: "Main Video URL (YouTube)",
        type: "url",
        required: false,
      },
      {
        name: "mainVideoType",
        label: "Video Type",
        type: "select",
        required: false,
        defaultValue: "youtube",
        options: [
          { label: "YouTube", value: "youtube" },
          { label: "Vimeo", value: "vimeo" },
        ],
      },
      {
        name: "clientName",
        label: "Client Name",
        type: "text",
        required: false,
      },
      {
        name: "projectType",
        label: "Project Type",
        type: "text",
        required: false,
      },
      {
        name: "budget",
        label: "Budget",
        type: "text",
        required: false,
      },
      {
        name: "area",
        label: "Area",
        type: "text",
        required: false,
      },
      {
        name: "tags",
        label: "Tags",
        type: "array",
        required: false,
      },
    ],
  },
];

export function getComponentSchema(type: string): ComponentSchema | undefined {
  return componentRegistry.find((c) => c.type === type);
}

export function getAllComponentTypes(): string[] {
  return componentRegistry.map((c) => c.type);
}
