import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const services = [
  { title: "Full Home Interiors", slug: "full-home-interiors", description: "End-to-end interior solution for your entire home. From living room to bedroom, kitchen to bathroom — we handle every detail.", shortDesc: "Complete home transformation", features: ["Full home 3D design", "Living room & bedroom design", "Modular kitchen", "Bathroom & balcony treatment", "Custom furniture & cabinetry"], stats: { priceRange: "₹8–25 Lakhs", deliveryTime: "60–90 Days", warranty: "10 Years" } },
  { title: "Modular Kitchen", slug: "modular-kitchen", description: "Custom modular kitchens with premium hardware, smart storage, and finishes that marry beauty with function.", shortDesc: "Smart, functional kitchens", features: ["Custom layout planning", "Premium laminates & shutters", "Hettich / Hafele / Blum hardware", "Quartz / granite countertops", "Smart storage solutions"], stats: { priceRange: "₹2–6 Lakhs", deliveryTime: "21–30 Days", warranty: "10 Years" } },
  { title: "Living Room Interiors", slug: "living-room-interiors", description: "Curated furniture, accent walls, lighting, and decor that transforms your living room into a statement space.", shortDesc: "Statement living spaces", features: ["False ceiling & lighting design", "Feature wall treatment", "Custom TV unit & seating", "Curtain & accessory curation", "Full colour palette"], stats: { priceRange: "₹1.5–4 Lakhs", deliveryTime: "21–35 Days", warranty: "10 Years" } },
  { title: "Bedroom Interiors", slug: "bedroom-interiors", description: "Serene, personalised bedrooms with wardrobe solutions, upholstered headboards, and calming palettes.", shortDesc: "Personal bedroom sanctuaries", features: ["Custom wardrobe design", "Upholstered headboard", "False ceiling with mood lighting", "Dresser & study unit", "Compact storage solutions"], stats: { priceRange: "₹1–3 Lakhs", deliveryTime: "15–25 Days", warranty: "10 Years" } },
  { title: "Wardrobe Design", slug: "wardrobe-design", description: "Floor-to-ceiling wardrobes designed around your lifestyle — sliding, hinged, or walk-in options.", shortDesc: "Floor-to-ceiling wardrobes", features: ["Sliding & hinged door options", "Walk-in wardrobe design", "Interior compartment planning", "Shoe racks & accessories", "Premium finishes"], stats: { priceRange: "₹0.8–2 Lakhs", deliveryTime: "10–20 Days", warranty: "10 Years" } },
  { title: "Luxury Furniture", slug: "luxury-furniture", description: "Custom handcrafted furniture pieces that elevate every room with exceptional craftsmanship.", shortDesc: "Handcrafted luxury pieces", features: ["Custom sofa & seating", "Dining tables & chairs", "Bed frames & headboards", "Premium wood & upholstery", "Bespoke design service"], stats: { priceRange: "₹1–5 Lakhs", deliveryTime: "30–45 Days", warranty: "10 Years" } },
];

const portfolioProjects = [
  { title: "Natural Perseverance", slug: "natural-perseverance", category: "Other", location: "Hyderabad", description: "A harmonious blend of natural materials and modern aesthetics creating a serene living environment.", image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80", images: ["https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80","https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80","https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80"], mainVideoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", mainVideoType: "YOUTUBE", clientName: "Mr. & Mrs. Sharma", projectType: "3BHK Apartment", budget: "₹ 27 Lakhs", area: "2,400 sq ft", featured: true, status: "PUBLISHED" },
  { title: "Lustrous Home in The Sky", slug: "lustrous-home-in-the-sky", category: "Penthouse", location: "Banjara Hills, Hyderabad", description: "A penthouse that captures the sky — floor-to-ceiling windows, reflective surfaces, and an ethereal palette.", image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80", images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80","https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&q=80","https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80"], mainVideoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", mainVideoType: "YOUTUBE", clientName: "Mr. Reddy", projectType: "4BHK Penthouse", budget: "₹ 45 Lakhs", area: "3,500 sq ft", featured: true, status: "PUBLISHED" },
  { title: "Euphoric Walls", slug: "euphoric-walls", category: "Villa", location: "Gachibowli, Hyderabad", description: "Vibrant walls that tell stories — bold colours, textured finishes, and artistic expression throughout.", image: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&q=80", images: ["https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&q=80","https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80","https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80"], mainVideoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", mainVideoType: "YOUTUBE", clientName: "Ms. Priya", projectType: "3BHK Villa", budget: "₹ 32 Lakhs", area: "2,800 sq ft", featured: true, status: "PUBLISHED" },
  { title: "Modern Home Close To Nature", slug: "modern-home-close-to-nature", category: "Apartment", location: "Kondapur, Hyderabad", description: "Bringing the outdoors in — natural light, indoor plants, and organic materials create a biophilic sanctuary.", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80", images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80","https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80","https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80"], mainVideoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", mainVideoType: "YOUTUBE", clientName: "Mr. Kumar", projectType: "2BHK Apartment", budget: "₹ 18 Lakhs", area: "1,800 sq ft", featured: false, status: "PUBLISHED" },
  { title: "Kitchens Descended From The Heavens", slug: "kitchens-descended-from-the-heavens", category: "Kitchen", location: "Jubilee Hills, Hyderabad", description: "A divine kitchen space — celestial lighting, heavenly finishes, and god-tier functionality.", image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80", images: ["https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80","https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80","https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80"], mainVideoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", mainVideoType: "YOUTUBE", clientName: "Mrs. Gupta", projectType: "Modular Kitchen", budget: "₹ 8 Lakhs", area: "350 sq ft", featured: false, status: "PUBLISHED" },
  { title: "Breach The Boring!", slug: "breach-the-boring", category: "Apartment", location: "Madhapur, Hyderabad", description: "Breaking all conventions — unconventional layouts, daring colour choices, and unexpected design elements.", image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80", images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80","https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80","https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&q=80"], mainVideoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", mainVideoType: "YOUTUBE", clientName: "Mr. & Mrs. Singh", projectType: "3BHK Apartment", budget: "₹ 25 Lakhs", area: "2,200 sq ft", featured: false, status: "PUBLISHED" },
  { title: "Modern Life, Contemporary Living", slug: "modern-life-contemporary-living", category: "Apartment", location: "HITEC City, Hyderabad", description: "Clean lines, minimal ornamentation, and maximum functionality — contemporary living at its finest.", image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80", images: ["https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80","https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80"], mainVideoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", mainVideoType: "YOUTUBE", clientName: "Mr. Venkat", projectType: "2BHK Apartment", budget: "₹ 16 Lakhs", area: "1,600 sq ft", featured: false, status: "PUBLISHED" },
  { title: "Luxury Wrapped With Gold", slug: "luxury-wrapped-with-gold", category: "Villa", location: "Banjara Hills, Hyderabad", description: "Opulence redefined — gold accents, marble surfaces, and luxurious textures create an atmosphere of grandeur.", image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80", images: ["https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80","https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80","https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&q=80"], mainVideoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", mainVideoType: "YOUTUBE", clientName: "Dr. & Mrs. Rao", projectType: "5BHK Villa", budget: "₹ 65 Lakhs", area: "4,500 sq ft", featured: false, status: "PUBLISHED" },
];

const testimonials = [
  { type: "GOOGLE", name: "Priya Sharma", location: "Jubilee Hills, Hyderabad", review: "Aertsen transformed our 3BHK into an absolute dream. The team was professional, transparent with costs, and delivered 5 days ahead of schedule.", rating: 5 },
  { type: "GOOGLE", name: "Rajesh Kumar", location: "Banjara Hills, Hyderabad", review: "Best interior designers in Hyderabad — hands down. No hidden costs, stunning 3D renders before work began, and the final result matched every pixel.", rating: 5 },
  { type: "GOOGLE", name: "Anita Reddy", location: "Gachibowli, Hyderabad", review: "We were nervous about our first home renovation. Aertsen made the entire experience stress-free and joyful. From design to handover in 78 days.", rating: 5 },
  { type: "VIDEO", name: "Mr. Cyril", location: "EIPL Cornerstone, Manikonda", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" },
  { type: "VIDEO", name: "Mr. Sai Kumar", location: "Honer Aquantis, Gopanpally", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" },
  { type: "VIDEO", name: "Mr. & Mrs. Vaishnavi and Rohit", location: "GHR Titania, Serilingampalle", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" },
];

const faqs = [
  { question: "What is the cost of full home interiors in Hyderabad?", answer: "The cost of full home interiors in Hyderabad typically ranges from ₹8 lakhs to ₹25 lakhs depending on the size of your home, quality of materials, and scope of work. We provide a detailed Bill of Quantities (BOQ) upfront so you know exactly what you're paying for.", category: "pricing" },
  { question: "How long does it take to complete home interiors?", answer: "Full home interiors typically take 60–90 days from design freeze to handover. Modular kitchens take 21–30 days, and individual rooms like bedrooms or living rooms take 15–35 days depending on scope.", category: "timeline" },
  { question: "Do you provide only modular kitchen or single room interiors?", answer: "Yes, absolutely. While we specialise in full home interiors, we also offer individual services like modular kitchens, living room design, bedroom interiors, and wardrobe design. Every service gets the same attention to detail.", category: "services" },
  { question: "What makes Aertsen Living different?", answer: "Aertsen stands apart through our in-house manufacturing facility, European-grade materials, complete transparency in pricing, trained in-house designers, and a 10-year warranty. We don't outsource — every piece is crafted under our supervision.", category: "general" },
  { question: "Do you offer customized interior designs?", answer: "Every design we create is 100% customised. We don't use templates. Our designers work closely with you to understand your lifestyle, preferences, and aspirations before creating a design that's uniquely yours.", category: "design" },
  { question: "Can I visit your factory?", answer: "Yes, we welcome factory visits! Our manufacturing facility is in Hyderabad. You can see the CNC precision cutting, quality control processes, and material selection firsthand. Book a visit through our consultation form.", category: "general" },
  { question: "Do you provide warranty on interiors?", answer: "Yes, we provide a comprehensive 10-year warranty on all our interiors. This covers structural integrity, hardware functionality, and finish quality. We also offer lifetime support for maintenance and repairs.", category: "warranty" },
];

const milestones = [
  { number: "1000", suffix: "+", label: "Projects Delivered" },
  { number: "1500", suffix: "+", label: "Happy Customers" },
  { number: "10", suffix: " yrs", label: "Warranty Provided" },
  { number: "200", suffix: "+", label: "Aertsen Crew" },
];

const timelineEvents = [
  { date: "Nov 2019", title: "Nirmaan group established", description: "The foundation was laid with the establishment of Nirmaan group, marking the beginning of our journey in the interiors industry." },
  { date: "Jul 2020", title: "Aertsen started as bootstrap", description: "Aertsen was born as a bootstrapped venture with a vision to transform home interiors in Hyderabad." },
  { date: "Sep 2020", title: "Hi-Living Series launched", description: "Our first product line — the Hi-Living Series — was launched, offering premium modular solutions." },
  { date: "Oct 2020", title: "First Experience Centre", description: "Opened our first Experience Centre where customers could see, touch, and feel our work before committing." },
  { date: "Nov 2020", title: "20 employees, first project", description: "Grew to 20 team members and delivered our first complete home interior project." },
  { date: "Feb 2021", title: "Operations in Vijayawada & Guntur", description: "Expanded operations to Vijayawada and Guntur, bringing our design expertise to more cities." },
  { date: "May 2021", title: "25th project, 35 employees", description: "Milestone of 25 completed projects and a growing team of 35 passionate individuals." },
  { date: "Jun 2021", title: "Easy Care series launched", description: "Introduced the Easy Care series — low-maintenance, high-durability interiors for busy families." },
  { date: "Sep 2021", title: "Own manufacturing facility", description: "Established our own in-house manufacturing facility for complete quality control." },
  { date: "Dec 2021", title: "75th project, 60+ employees", description: "Reached 75 projects with a team of over 60 dedicated professionals." },
  { date: "Jun 2022", title: "7+ cities, 100+ employees, 100+ homes", description: "Expanded to 7+ cities with 100+ employees and 100+ completed homes — a testament to our growth." },
];

const pages = [
  { title: "Home", slug: "home", status: "PUBLISHED", sections: [
    { type: "aertsen-hero-slider", order: 0, props: { slides: [{ title: "Design Services", subtitle: "Built Around You", image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1920&q=80" },{ title: "Natural Perseverance", subtitle: "Where light meets tranquility", image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1920&q=80" },{ title: "Euphoric Walls", subtitle: "Contemporary elegance", image: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1920&q=80" },{ title: "Modern Living", subtitle: "Simplicity in every detail", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80" }] }},
    { type: "aertsen-services-grid", order: 1, props: { label: "Our Expertise", title: "Design Services", accentWord: "Built Around You", services: [{ number: "01", title: "Full Home Interiors", description: "End-to-end interior solution", link: "/services/full-home-interiors" },{ number: "02", title: "Modular Kitchen", description: "Custom kitchen solutions", link: "/services/modular-kitchen" },{ number: "03", title: "Living Room Interiors", description: "Statement living spaces", link: "/services/living-room-interiors" },{ number: "04", title: "Bedroom Interiors", description: "Serene bedroom retreats", link: "/services/bedroom-interiors" },{ number: "05", title: "Wardrobe Design", description: "Floor-to-ceiling wardrobes", link: "/services/wardrobe-design" },{ number: "06", title: "Luxury Furniture", description: "Handcrafted luxury pieces", link: "/services/luxury-furniture" }] }},
    { type: "aertsen-milestones", order: 2, props: { milestones: [{ number: "1000", suffix: "+", label: "Projects Delivered" },{ number: "1500", suffix: "+", label: "Happy Customers" },{ number: "10", suffix: " yrs", label: "Warranty Provided" },{ number: "200", suffix: "+", label: "Aertsen Crew" }] }},
    { type: "aertsen-why-choose", order: 3, props: { label: "Why Aertsen", title: "The Aertsen", accentWord: "Difference", items: [{ number: "01", title: "European Standards", description: "Every product reflects European quality at Indian prices" },{ number: "02", title: "In-House Factory", description: "Own manufacturing in Hyderabad" },{ number: "03", title: "Complete Transparency", description: "Materials, finishes, specs documented" },{ number: "04", title: "Trained Designers", description: "In-house team, no third-party" }] }},
    { type: "aertsen-portfolio-slider", order: 4, props: { label: "Our Work", title: "Finest Projects", accentWord: "We've Crafted", projects: [{ title: "Natural Perseverance", category: "Other", image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80" },{ title: "Lustrous Home in The Sky", category: "Penthouse", image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80" },{ title: "Euphoric Walls", category: "Villa", image: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&q=80" },{ title: "Modern Home Close To Nature", category: "Apartment", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80" },{ title: "Kitchens Descended From The Heavens", category: "Kitchen", image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80" },{ title: "Breach The Boring!", category: "Apartment", image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80" },{ title: "Modern Life, Contemporary Living", category: "Apartment", image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80" },{ title: "Luxury Wrapped With Gold", category: "Villa", image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80" }] }},
    { type: "aertsen-process-wheel", order: 5, props: { title: "Steps to give your home an", accentWord: "Aertsen Makeover", steps: [{ number: "01", title: "Design Pitch", description: "Requirement discussion, tentative quotation, 10% onboarding", checklist: ["Requirement discussion & moodboard", "Tentative quotation shared", "Onboarding with 10% confirmation"] },{ number: "02", title: "Count on our Designers", description: "3D designs, materials finalized, sign-off", checklist: ["3D designs & layouts presented", "Materials & finishes finalised", "Design sign-off & timeline confirmed"] },{ number: "03", title: "Dreams Under Construction", description: "Handover to execution, on-site work, progress updates", checklist: ["Project handover to execution team", "On-site work begins", "Milestone-based progress updates"] },{ number: "04", title: "Step into your Dream Home", description: "Quality checks, walkthrough, warranty docs", checklist: ["Quality checks completed", "Final walkthrough & handover", "Warranty & documents handed over"] }] }},
    { type: "aertsen-factory", order: 6, props: { label: "Our Factory", title: "Where Craftsmanship", accentWord: "Meets Technology", description: "We combine traditional woodworking expertise with modern manufacturing technology.", highlights: [{ title: "CNC Precision", description: "Computer-controlled cutting" },{ title: "European Hardware", description: "Hettich, Hafele, Blum" },{ title: "Multi-Level QC", description: "Multiple quality checks" },{ title: "100% In-House", description: "No outsourcing" }], videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" }},
    { type: "aertsen-google-reviews", order: 7, props: { label: "Client Reviews", title: "Trusted by Homeowners", accentWord: "Across Hyderabad", googleScore: "4.9", reviewCount: "150+", reviews: [{ name: "Priya Sharma", rating: 5, review: "Aertsen transformed our 3BHK into an absolute dream. Professional, transparent, and delivered ahead of schedule.", location: "Jubilee Hills" },{ name: "Rajesh Kumar", rating: 5, review: "Best interior designers in Hyderabad. No hidden costs, stunning 3D renders, and the final result matched every pixel.", location: "Banjara Hills" },{ name: "Anita Reddy", rating: 5, review: "We were nervous about our first renovation. Aertsen made it stress-free and joyful. From design to handover in 78 days.", location: "Gachibowli" }] }},
    { type: "aertsen-video-testimonials", order: 8, props: { label: "Video Stories", title: "Real Homes.", accentWord: "Real Stories.", videos: [{ thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg", name: "Mr. Cyril", location: "EIPL Cornerstone, Manikonda", youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" },{ thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg", name: "Mr. Sai Kumar", location: "Honer Aquantis, Gopanpally", youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" },{ thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg", name: "Mr. & Mrs. Vaishnavi and Rohit", location: "GHR Titania, Serilingampalle", youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" }] }},
    { type: "aertsen-final-cta", order: 9, props: { label: "Start Your Journey", title: "Ready to Transform", accentWord: "Your Home?", body: "Book a free consultation with our design experts and take the first step towards your dream home.", buttons: [{ label: "Book Free Consultation", url: "/contact", type: "primary" },{ label: "Call 040-4189-5555", url: "tel:040-4189-5555", type: "phone" },{ label: "WhatsApp Us", url: "https://wa.me/919030444503", type: "whatsapp" }] }},
    { type: "aertsen-faq", order: 10, props: { label: "Got Questions?", title: "Frequently Asked Questions", accentWord: "About Home Interiors", intro: "Everything you need to know about our interior design services.", faqs: [{ question: "What is the cost of full home interiors in Hyderabad?", answer: "The cost ranges from ₹8 lakhs to ₹25 lakhs depending on home size and material quality." },{ question: "How long does it take to complete home interiors?", answer: "Full home interiors take 60–90 days from design freeze to handover." },{ question: "Do you provide only modular kitchen or single room interiors?", answer: "Yes, we offer individual services like modular kitchens, living room, and bedroom design." },{ question: "What makes Aertsen Living different?", answer: "In-house manufacturing, European materials, transparent pricing, and 10-year warranty." },{ question: "Do you offer customized interior designs?", answer: "Every design is 100% customised to your lifestyle and preferences." },{ question: "Can I visit your factory?", answer: "Yes, our manufacturing facility in Hyderabad welcomes visitors." },{ question: "Do you provide warranty on interiors?", answer: "Yes, we provide a comprehensive 10-year warranty on all interiors." }] }},
  ]},
  { title: "About Us", slug: "about", status: "PUBLISHED", sections: [
    { type: "aertsen-about-hero", order: 0, props: { eyebrow: "About Us", title: "Aertsen stands as one of India's", accentWord: "Most Trusted Home Interior Brands", subtitle: "A one-stop solution for all your home interior needs with in-house manufacturing and transparent pricing." }},
    { type: "aertsen-who-we-are", order: 1, props: { label: "Who We Are", title: "Hyderabad's Most Trusted", accentWord: "Interior Studio", body: ["Aertsen is a premier interior design studio based in Hyderabad, offering end-to-end home interior solutions.","With our own manufacturing facility and a team of 200+ trained professionals, we deliver exceptional quality at competitive prices."], stats: [{ number: "1500", suffix: "+", label: "Projects Delivered" },{ number: "200", suffix: "+", label: "Aertsen Crew" },{ number: "10", suffix: "yr", label: "Warranty" },{ number: "4.9", suffix: "★", label: "Google Rating" }], image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80" }},
    { type: "aertsen-story", order: 2, props: { label: "Our Story", title: "How We", accentWord: "Began", body: ["Founded in 2014 as a furniture importing business, we evolved into Aertsen Living in 2020 with a vision to revolutionise home interiors in Hyderabad.","Today, we are one of the most trusted names in interior design, with our own factory and a growing family of happy homeowners."], image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80" }},
    { type: "aertsen-vision-mission", order: 3, props: { label: "What Drives Us", title: "Vision &", accentWord: "Mission", vision: { title: "Vision", text: "To make exceptional design accessible to every homeowner in India through quality craftsmanship and transparent pricing." }, mission: { title: "Mission", text: "To be the pioneer in the home interior market by delivering European-standard quality at Indian prices." } }},
    { type: "aertsen-promises", order: 4, props: { label: "Our Commitments", title: "Our", accentWord: "Promises", commitments: ["Maintain highest standards of design excellence","Offer best-in-class customer experience","Transparent pricing and quality craftsmanship","Be earth-friendly and contribute to shaping the future"], cards: [{ number: "01", title: "Detailed Craftsmanship", description: "Every detail is meticulously crafted to perfection." },{ number: "02", title: "Design Driven", description: "Design is at the heart of everything we create." },{ number: "03", title: "Affordable Luxury", description: "European quality at Indian prices." }] }},
    { type: "aertsen-founders", order: 5, props: { label: "The People Behind Aertsen", title: "Meet the", accentWord: "Founders", founders: [{ name: "Manidhar Anumula", role: "Co-Founder & Director", bio: "With a vision to transform home interiors, Manidhar leads Aertsen with passion and innovation.", linkedIn: "#" },{ name: "Vinay Addagiri", role: "Co-Founder & Director", bio: "Vinay brings operational excellence and strategic vision to every project Aertsen undertakes.", linkedIn: "#" }] }},
    { type: "aertsen-timeline", order: 6, props: { label: "Since 2019", title: "Our", accentWord: "Journey", events: [{ date: "Nov 2019", title: "Nirmaan group established" },{ date: "Jul 2020", title: "Aertsen started as bootstrap" },{ date: "Sep 2020", title: "Hi-Living Series launched" },{ date: "Oct 2020", title: "First Experience Centre" },{ date: "Nov 2020", title: "20 employees, first project" },{ date: "Feb 2021", title: "Operations in Vijayawada & Guntur" },{ date: "May 2021", title: "25th project, 35 employees" },{ date: "Jun 2021", title: "Easy Care series launched" },{ date: "Sep 2021", title: "Own manufacturing facility" },{ date: "Dec 2021", title: "75th project, 60+ employees" },{ date: "Jun 2022", title: "7+ cities, 100+ employees, 100+ homes" }] }},
    { type: "aertsen-factory-video", order: 7, props: { label: "In-House Manufacturing", title: "Our", accentWord: "Factory", videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg" }},
    { type: "aertsen-about-cta", order: 8, props: { label: "Start Your Journey", title: "Let's Design Your", accentWord: "Dream Home", body: "Ready to transform your space? Book a free consultation with our design experts.", buttonText: "Book Free Consultation", buttonUrl: "/contact", phone: "040-4189-5555" }},
  ]},
  { title: "Services", slug: "services", status: "PUBLISHED", sections: [
    { type: "aertsen-services-hero", order: 0, props: { eyebrow: "Our Services", title: "Every Space. Every Detail.", accentWord: "Perfectly Designed.", subtitle: "6 specialised interior design services, all backed by our own factory, timely delivery and 10-year warranty." }},
    { type: "aertsen-services-cards", order: 1, props: { services: [{ title: "Full Home Interiors", description: "End-to-end interior solution", image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80", link: "/services/full-home-interiors", features: ["3BHK+","Turnkey"] },{ title: "Modular Kitchen", description: "Custom L-shaped, U-shaped & island", image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80", link: "/services/modular-kitchen", features: ["Premium Hardware","Smart Storage"] },{ title: "Living Room", description: "Curated furniture, accent walls, lighting", image: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80", link: "/services/living-room-interiors", features: ["False Ceiling","Feature Wall"] },{ title: "Bedroom", description: "Serene, personalised bedrooms", image: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&q=80", link: "/services/bedroom-interiors", features: ["Wardrobe","Mood Lighting"] },{ title: "Wardrobe Design", description: "Floor-to-ceiling wardrobes", image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80", link: "/services/wardrobe-design", features: ["Sliding/Hinged","Walk-in"] },{ title: "Luxury Furniture", description: "Custom handcrafted furniture", image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80", link: "/services/luxury-furniture", features: ["Bespoke","Premium Wood"] }] }},
    { type: "aertsen-services-cta", order: 2, props: { label: "Get Started", title: "Not Sure Where to Start?", body: "Book a free consultation. Our experts will help you plan your dream home.", buttonText: "Book Free Consultation", buttonUrl: "/contact", secondaryButtonText: "Try AI Design Tool", secondaryButtonUrl: "#" }},
  ]},
  { title: "Portfolio", slug: "portfolio", status: "PUBLISHED", sections: [
    { type: "aertsen-portfolio-hero", order: 0, props: { eyebrow: "Our Portfolio", title: "Spaces Crafted With", accentWord: "Intention & Heart", subtitle: "Over 1,500 homes transformed across Hyderabad with European standards and Indian prices." }},
    { type: "aertsen-project-list", order: 1, props: {}},
  ]},
];

async function main() {
  console.log("🌱 Seeding Aertsen content...\n");

  for (const s of services) {
    await prisma.service.upsert({ where: { slug: s.slug }, update: s, create: { ...s, sortOrder: services.indexOf(s) } });
  }
  console.log(`✅ Services: ${services.length}`);

  for (const p of portfolioProjects) {
    await prisma.portfolioProject.upsert({ where: { slug: p.slug }, update: p, create: { ...p, sortOrder: portfolioProjects.indexOf(p) } });
  }
  console.log(`✅ Portfolio Projects: ${portfolioProjects.length}`);

  for (const t of testimonials) {
    await prisma.testimonial.create({ data: { ...t, sortOrder: testimonials.indexOf(t) } });
  }
  console.log(`✅ Testimonials: ${testimonials.length}`);

  for (const f of faqs) {
    await prisma.fAQ.create({ data: { ...f, sortOrder: faqs.indexOf(f) } });
  }
  console.log(`✅ FAQs: ${faqs.length}`);

  for (const m of milestones) {
    await prisma.milestone.create({ data: { ...m, sortOrder: milestones.indexOf(m) } });
  }
  console.log(`✅ Milestones: ${milestones.length}`);

  for (const e of timelineEvents) {
    await prisma.timelineEvent.create({ data: { ...e, sortOrder: timelineEvents.indexOf(e) } });
  }
  console.log(`✅ Timeline Events: ${timelineEvents.length}`);

  for (const p of pages) {
    const existing = await prisma.page.findUnique({ where: { slug: p.slug } });
    if (!existing) {
      const { sections: secs, ...pageData } = p;
      await prisma.page.create({ data: { ...pageData, sections: { create: secs.map(s => ({ type: s.type, order: s.order, props: s.props })) } } });
      console.log(`✅ Created page: ${p.title}`);
    } else {
      console.log(`⏭️ Page exists: ${p.title}`);
    }
  }

  console.log("\n🎉 Aertsen seeding complete!");
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
